apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ersanjeev/devops-challanges
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/imsanjeevkumar/gitops.git
    targetRevision: HEAD  
    path: devops-challanges
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-challanges
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true